<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>ShopOperator</AssemblyName>
    <RootNamespace>ShopOperator</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="KubeOps.Operator" Version="9.*" />
  </ItemGroup>

</Project>
